print( "type(nil)", type(nil) )
print( "type(true)", type(true) )
print( "type(false)", type(false) )
print( "type(123)", type(123) )
print( "type(123.456)", type(123.456) )
print( "type(\"Hello World\")", type("Hello World") )
print( "type(io.stdin)", type(io.stdin) )
print( "type(print)", type(print) )
print( "type(type)", type(type) )
print( "type({})", type({}) )
print( "type(type(X))", type(type(X)) )
